# Generated by Django 5.0.1 on 2024-03-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_spiritual_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiritual',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='spiritual',
            name='img',
            field=models.ImageField(default=0, upload_to='images/spiritual/'),
        ),
    ]
