# Generated by Django 5.0.1 on 2024-03-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_spiritual_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiritual',
            name='img',
        ),
        migrations.AddField(
            model_name='spiritual',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='spiritual_images/'),
        ),
        migrations.AlterField(
            model_name='spiritual',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spiritual',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='spiritual',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spiritual',
            name='state_name',
            field=models.CharField(max_length=100),
        ),
    ]
