# Generated by Django 5.0.1 on 2024-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_spiritual_img_spiritual_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images/'),
        ),
    ]
